# Generated by Django 3.1.5 on 2021-01-11 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210107_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contry',
            options={},
        ),
    ]
